### ISSUE TITLE
KeySpec AT_KEYEXCHANGE

### ISSUE THREAD

**Issue by w8083** [patrickpr/YAOG#10]
Hi,
Is there any way to define the  KeySpec AT_KEYEXCHANGE.?

Thanks.

**Comment by patrickpr** [comment]
From openssl site about this ( [openssl pkcs12 create](https://www.openssl.org/docs/man1.1.1/man3/PKCS12_create.html) ): 

"This option was useful for old export grade software which could use signing only keys of arbitrary size but had restrictions on the permissible sizes of keys which could be used for encryption."

What is the use case for this ? Does MS software still uses it ?

**Comment by w8083** [comment]
Hi Patrickpr, thanks for your reply and update. yes that is one of the mandatory options for certificate to use in Microsoft SQL Server to encrypt connections using TLS.

This is the certificate requirement:
The certificate must be created by using the KeySpec option of AT_KEYEXCHANGE. Usually, the certificate's key usage property (KEY_USAGE) will also include key encipherment (CERT_KEY_ENCIPHERMENT_KEY_USAGE).

https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine?view=sql-server-ver15

Thanks in advance.

**Comment by patrickpr** [comment]
This just needs a quick patch on existing p12 export, so I will start working on it, and should release a new version next week.

**Comment by w8083** [comment]
sounds great Patrick! thank you very much.

**Comment by patrickpr** [comment]
Hi,

Made a quick change : now you can set the private key flag on p12 export : 
![image](https://user-images.githubusercontent.com/2913330/94994799-6145d100-059a-11eb-8010-67e8f064793d.png)

and it seems to do something :-) : 
![image](https://user-images.githubusercontent.com/2913330/94994834-8b978e80-059a-11eb-9b93-73819d798049.png)
 
But I don"t have anything to test it on.

I attached below the updated version of yaog. It's only the .exe, so you need to put it in your current yaog directory replacing your exe.

**Can you make some test and give me feedback with this version ?**

[YetAnotherOpensslGui.zip](https://github.com/patrickpr/YAOG/files/5321870/YetAnotherOpensslGui.zip)

Note : you need to be currently using the latest yaog version.

**Comment by w8083** [comment]
Hi Patrick, that's great. I'll download and test it.  appreciate your help.
I'll keep you posted about the result.

**Comment by w8083** [comment]
Hi Patrick, good news. I could test it and it is working as expected. now MSSQL is able to recognize the certificate and I can use it.
Thank you very much. congrats!  very nice tool!

![image](https://user-images.githubusercontent.com/71990142/95650906-3ff46000-0b19-11eb-8331-66f9e265be31.png)

**Comment by patrickpr** [comment]
Ok, thanks for testing.
I will finish the encryptions parameters of PKCS12 and release a new version soon.

**Comment by patrickpr** [comment]
@w8083 : the new release (1.1.2) is available, I suggest you download it to replace your current version.

**Comment by w8083** [comment]
thanks @patrickpr I'll do.
