### ISSUE TITLE
Impossible generate certs

### ISSUE THREAD

**Issue by brothercorvo** [patrickpr/YAOG#12]
Whatever configuration I select I get an error similar to:
Lib : asn1 encoding routines, doing : ASN1_mbstring_ncopy, reason : string too long (13/122/151)

**Comment by patrickpr** [comment]
Hi,

Did you check this : [Issue #7](https://github.com/patrickpr/YAOG/issues/7) ?

Can you provide a screenshot of the configuration that generates this error ?

Regards,

Patrick

**Comment by brothercorvo** [comment]
here you go. It is the quantity of text that you have in subject
![image](https://user-images.githubusercontent.com/60719165/102230801-ad2ec380-3ec3-11eb-8c24-8afcb842be9c.png)

**Comment by patrickpr** [comment]
Hi,

Country is limited to two caracters : it is supposed to be like Internet TLD, and in this case put 'ca' or 'CA'.
Reference : X520countryName defined in [RFC5280](https://tools.ietf.org/html/rfc5280 ) using codes from [ISO 3166](https://fr.wikipedia.org/wiki/ISO_3166)

Tell me if this works better.

Regards

**Comment by brothercorvo** [comment]
Ok that solved the issue. Probably would be good to limit the text input to 2 chars.
