### ISSUE TITLE
Update OpenSSL to version 1.1.1

### ISSUE THREAD

**Issue by me21** [patrickpr/YAOG#4]
Hello,

The latest version of OpenSSL is now 1.1.1. Can you please update the version in your repo?
Or maybe there's an option to use custom locations for OpenSSL include and lib directories (to use the version installed on the build host)?

**Comment by patrickpr** [comment]
Hi, 

The program loads the ssl libraries dynamically, so you can simply replace the ssl DLL (libeay, libssl, ssleay), (or remove them completly to use the ones in the system defined dll locations).

This might not work if version 1.1.1 made significant changes : I'll have a look and make an update this month.

Happy to see there is some users other than me of this !

**Comment by patrickpr** [comment]
Update : I have errors with encrypted keys in openssl 1.1.1. 
Working on it.

**Comment by patrickpr** [comment]
1.0.2 is out. It's compiled with openssl 1.1.1 for all crypto operations.
