### ISSUE TITLE
Can't find the exe

### ISSUE THREAD

**Issue by hvddrift** [patrickpr/YAOG#6]
Hi Patrick, I am looking at the YAGO project.

Looking at the instructions it has: Just unzip and run the exe. All dependencies (SSL & Qt) are packaged inside the zip file.

But, I may be not seeing it, where do I download the exe file from?

**Comment by patrickpr** [comment]
Hi, 

On the [main page](https://github.com/patrickpr/YAOG) , select "releases' then download latest version.
Or just click [HERE](https://github.com/patrickpr/YAOG/releases/download/1.1.0/YAOG.zip)

/Patrick
