### ISSUE TITLE
interface not printing well

### ISSUE THREAD

**Issue by 8mccm8** [patrickpr/YAOG#8]
Hi,

I'm using 3840x2160 resolution with 200% windows scale and the interface looks like this

![image](https://user-images.githubusercontent.com/2759580/89871811-55e8b180-dbb8-11ea-8dec-a2ff9b60287f.png)

**Comment by patrickpr** [comment]
Hi,
I'lll have a look when I get back from holydays (around August 24).
/Patrick

**Comment by patrickpr** [comment]
Hi,

I changed the application attribute to enable High DPI scaling, so the windows should look better, but it will also be much bigger (200% in your case).

It's not a perfect solution but the other way would need to copletly rewrite the main window....

Get the latest version (1.1.1) of yaog and tell me if it is better.
